---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.34.34"}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: gbarbieru/xenial 

suites:
  - name: default
    run_list:
      - recipe[awesome_customers_ubuntu::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
